services:
  - type: web
    name: seminario-actualizacion-gradio
    runtime: python
    plan: free
    rootDir: clase-05
    buildCommand: pip install -r requirements-gradio.txt
    startCommand: python gradio_app.py
